### ISSUE TITLE
Skapa databas för alla böcker så kunden kan nyttja dessa genom att dessa kan *lånas* och *lämnas* och *hittas* i databasen

### ISSUE THREAD

**Issue by nadiasGame** [nadiasGame/power.dolphins#14]
skapa en Json fil där vi "hårdkokar" in några böcker
importera books.json du skapade ovan och lägg till den i initialState för böckerna
skapa några reducer funktioner för att lägga till, ta bort och redigera böcker
lägg till parallella actions för dessa reducer actions:en

DOD: vi har en fin redux store med alla böcker där man kan ta bort o lägga till böcker

**Comment by Kybbe** [comment]
done with #75
